- hosts: localhost
  vars:
    aws_ip: [ Public IP : yes/no ]
    aws_key: [ SSH_Key to use ]
    aws_image: [ImageAMI]
    aws_region: [Region]
    aws_sub: [Subnet]
    aws_instance: [Instance_type]
    aws_count: [Number of servers to deploy]
    aws_group: [Sec group to use]
  connection: local
  roles:
  - ec2
  
